version: '3.8'
services: 
    app:
        container_name: react-app
        build: 
            context: ./
        ports:
            - "3000:80"
        networks:
            - mynetwork
        depends_on:
            - "api"
    api:
        container_name: flask-api
        build: ./backend
        env_file:
            - ./.env
        ports: 
            - 5000:5000
        networks:
            - mynetwork
networks:
    mynetwork:
