

@apiUrl = https://api.openweathermap.org/data/2.5/weather
@flask_url=http://127.0.0.1:5000/
@token = xx
@city = Curitiba

###
GET {{apiUrl}}?q={{city}}&appid={{token}}

###
GET {{flask_url}}weather/{{city}}
###
GET {{flask_url}}weather?max=1